name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - numba
  - pandas
  - dask
  - distributed
  - coverage
  - flake8
  - flake8-docstrings
  - black
  - pytest-cov
  - jupyterlab
  - appmode
  - ipywidgets
  - nodejs
